### ISSUE TITLE
data.js from url data real?

### ISSUE THREAD

**Issue by IldeNet** [dimxasnewfrozen/VG-Telemtry-Timeline#1]
Is it possible to include a button to supply a URL of a real telemetry?
for example:
https://gl-prod-us-east-1.s3.amazonaws.com/assets/semc-vainglory/eu/2017/03/18/01/52/9998f53f-0b7d-11e7-8e12-0242ac110008-telemetry.json

**Comment by IldeNet** [comment]
I have tried to save the real telemetry data in data.js but it is not supported yet.Thank you for your great work and time invested.

**Comment by dimxasnewfrozen** [comment]
I just confirmed that the data from that json does indeed work. I updated data.js with the data from this file:

https://github.com/dimxasnewfrozen/VG-Telemtry-Timeline/blob/master/js/data.js

Can you describe the issues you were having?

**Comment by IldeNet** [comment]
But data.js file does not contain updated values, since madglory has changed the information. A recent telemetry file can be found in the first comment.

**Comment by dimxasnewfrozen** [comment]
Yes. Please look at this commit: c819129f620d6fd4437b497be3b41bc2098af461

I replaced the data in data.js with the data from the file you provided. This IS the updated data in data.js.

**Comment by IldeNet** [comment]
Thank you very much for your great work, then go home and prove it.

**Comment by IldeNet** [comment]
is working if i add line "data =" to file data.js
thank you for you work.

**Comment by dimxasnewfrozen** [comment]
Yup. Exactly. 👍

**Comment by IldeNet** [comment]
But you removed the button to add source from url. Can not create it? Thank you
